/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecture3.classer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
